AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Collateral Valuation Service - Vehicle valuation with DDD architecture

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Environment:
      Variables:
        NODE_ENV: production

Parameters:
  NadaApiKey:
    Type: String
    Description: NADA Guides API Key
    NoEcho: true
    Default: ''

  KBBApiKey:
    Type: String
    Description: Kelley Blue Book API Key
    NoEcho: true
    Default: ''

  ChromeApiKey:
    Type: String
    Description: Chrome Data API Key
    NoEcho: true
    Default: ''

Resources:
  CollateralValuationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  CollateralValuationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CollateralValuationService
      CodeUri: ./
      Handler: dist/presentation/handlers/lambda.handler
      Description: Vehicle valuation service with multiple provider support
      Environment:
        Variables:
          NADA_API_KEY: !Ref NadaApiKey
          NADA_API_URL: https://api.nadaguides.com
          KBB_API_KEY: !Ref KBBApiKey
          KBB_API_URL: https://api.kbb.com
          CHROME_API_KEY: !Ref ChromeApiKey
          CHROME_API_URL: https://api.chromedata.com
      Events:
        GetValuation:
          Type: Api
          Properties:
            RestApiId: !Ref CollateralValuationApi
            Path: /valuation
            Method: POST
        GetProviders:
          Type: Api
          Properties:
            RestApiId: !Ref CollateralValuationApi
            Path: /providers
            Method: GET
        OptionsValuation:
          Type: Api
          Properties:
            RestApiId: !Ref CollateralValuationApi
            Path: /valuation
            Method: OPTIONS
        OptionsProviders:
          Type: Api
          Properties:
            RestApiId: !Ref CollateralValuationApi
            Path: /providers
            Method: OPTIONS

  CollateralValuationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${CollateralValuationFunction}
      RetentionInDays: 14

Outputs:
  CollateralValuationApiUrl:
    Description: API Gateway endpoint URL for Collateral Valuation Service
    Value: !Sub https://${CollateralValuationApi}.execute-api.${AWS::Region}.amazonaws.com/prod/
    Export:
      Name: CollateralValuationApiUrl

  CollateralValuationFunctionArn:
    Description: Collateral Valuation Lambda Function ARN
    Value: !GetAtt CollateralValuationFunction.Arn
    Export:
      Name: CollateralValuationFunctionArn
